version: "2"

services:
#modificar archivo mongod
#repSet habilitar la replicacion
  mongo-master:
    image: mongo:4.2
    restart: always
    container_name: GRUPO16_MONGO_MASTER
    ports:
      - 2090:27017
    entrypoint: [ "/usr/bin/mongod", "--replSet", "bd2_grupo16", "--bind_ip_all"]

  mongo1:
    image: mongo:4.2
    restart: always
    container_name: GRUPO16_MONGO_01
    ports:
      - 2091:27017
    entrypoint: [ "/usr/bin/mongod", "--replSet", "bd2_grupo16", "--bind_ip_all"]

  mongo2:
    image: mongo:4.2
    restart: always
    container_name: GRUPO16_MONGO_02
    ports:
      - 2092:27017
    entrypoint: [ "/usr/bin/mongod", "--replSet", "bd2_grupo16", "--bind_ip_all"]

  mongo3:
    image: mongo:4.2
    restart: always
    container_name: GRUPO16_MONGO_03
    ports:
      - 2083:27017
    entrypoint: [ "/usr/bin/mongod", "--replSet", "bd2_grupo16", "--bind_ip_all"]

  mongo4:
    image: mongo:4.2
    restart: always
    container_name: GRUPO16_MONGO_04
    ports:
      - 2094:27017
    entrypoint: [ "/usr/bin/mongod", "--replSet", "bd2_grupo16", "--bind_ip_all"]
